name: Debug Secrets  # 工作流名称
on: workflow_dispatch  # 允许“手动触发”，方便测试

jobs:
  debug_secrets:  # 自定义任务名称
    runs-on: ubuntu-latest  # 运行的虚拟机环境
    environment: aliyun-sync-env
    steps:
      - name: Print Secrets  # 步骤名称
        run: |
          echo "Username: ${{ secrets.ALIYUN_USERNAME }}"
          echo "Password: ${{ secrets.ALIYUN_PASSWORD }}"
          echo "DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}"
          echo "DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}"
